model:
  base_learning_rate: 4.5e-6
  target: cogs.models.vqgan.VQModel
  params:
    image_key: "sketch"
    embed_dim: 256
    n_embed: 1024
    ddconfig:
      double_z: False
      z_channels: 256
      resolution: 256
      in_channels: 3
      out_ch: 3
      ch: 128
      ch_mult: [ 1,1,2,2,4]  # num_down = len(ch_mult)-1
      num_res_blocks: 2
      attn_resolutions: [16]
      dropout: 0.0

    lossconfig:
      target: cogs.modules.losses.vqperceptual.VQLPIPSWithDiscriminator
      params:
        disc_conditional: False
        disc_in_channels: 3
        disc_start: 10000
        disc_weight: 0.8
        codebook_weight: 1.0


data:
  target: main.DataModuleFromConfig
  params:
    batch_size: 2
    num_workers: 24
    train:
      target: cogs.data.sketch_style_label.SketchTrain
      params:
        config:
          size: 256
          sketch_path: # /path/to/pseudosketches
          image_path: # /path/to/corresponding/images
          style_path: # /path/to/style/images
          file_list: # /path/to/train/list.txt
    validation:
      target: cogs.data.sketch_style_label.SketchValidation
      params:
        config:
          size: 256
          sketch_path: # /path/to/pseudosketches
          image_path: # /path/to/corresponding/images
          style_path: # /path/to/style/images
          file_list: # /path/to/val/list.txt
